[ZV-308] init logging
ZveronHSE/platform-library pull request #2
Opened 2023-02-23 20:52 UTC by WolfAlm

2023-02-23 21:47 UTC, Schuyweiz requested changes

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +            logger.debug(Markers.aggregate(markers)) { "service: ${method.serviceName}" }
это нам не нужно, выключается и включается  логстешем

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/configuration/GrpcConfiguration.kt
> +@Order(Ordered.HIGHEST_PRECEDENCE)
почему такой приоритет?

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/entity/ApiGatewayEntity.kt
> +data class ApiGatewayEntity(
давай не будем это называть энтити, так как энтити все же используется для сущностей, который храним в бд

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +    fun MutableList<LogstashMarker>.addBodyToLog(key: String, json: String) {
а смысл это перекладывать в отдельный метод

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +        if (methodType == MethodType.REQUEST) {
этот иф элс очень тяжело читается, сначала логика завязана на тип метода, потому у нас возникает какое-то левое условие для другой ветки

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +        if (methodType == MethodType.REQUEST) {
а понял, это сразу и запросы и ответы. Кажется неочевидно. Мне кажется нужно, чтобы в коде четче читалось, что во второй ветке мы именно вариант с респонсом смотрим.

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +        val body = (message as GeneratedMessageV3)
можете через as? кастовать, чтобы в логах не падать еслт вдруг что-то идет не так

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
давай не будем привязывать имя интерцептора и пропертю к метадате. Тут кажется логичным, что работа идет с айдишником профиля, а не всей метадатой. 

И включать выключать кажется логичным отдельный компонент данных из метадаты, а не всю ее сразу. 

Я бы назвал это именно `ProfileIdInterceptor` или в этом духе.

И название сущности, которую мы тащим из метадаты в контекст другое нужно. `ApiGatewayElement` слишком общее название. А мы тут конкретно айдишник складываем

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/model/LogstashKey.kt
> +    const val ENDPOINT_KEY = "endpoint"
получается6 что эндпоинт это точка и по второму ключу мы определяем принимает он запрос или получает?

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/util/ApiGatewayUtils.kt
> +class ApiGatewayUtils {
может лучше `object`?

2023-02-23 21:47 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/GrpcProps.kt
> +    data class GrpcServerProps(
правильнее по дефолту везде логгирование будет вырубить, защита от дурака, если кто забудет

2023-02-23 21:48 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +    fun MutableList<LogstashMarker>.addBodyToLog(key: String, json: String) {
а там уже рефакторинг произошел последним коммитом)

2023-02-23 21:49 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +        val body = (message as GeneratedMessageV3)
там всегда по умолчанию сообщения и ответы только через контракт, они все наследуются от GeneratedMessageV3 -- это как налсдеоваться от Any)

2023-02-23 21:50 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
я решила так назвать сразу, потому что метаданные могут расшириться и будет класть не только юзер айди, так зачем привязываться так, если можно просто обобщенное название делать, а в поля будем класть всякие штуки

2023-02-23 22:01 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/configuration/GrpcConfiguration.kt
> +    @ConditionalOnMissingBean(LoggingClientInterceptor::class)
вот это не совсем понял, а может быть чтобы бин уже был до его инициализации?

2023-02-23 22:01 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +            logger.info(Markers.aggregate(markers)) { "$TYPE_CALL: ${method.serviceName}" }
почему сюда, а не в маркет тоже?

2023-02-23 22:01 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/GrpcProps.kt
> +@ConfigurationProperties(prefix = "platform.grpc")
а оно подсосется? Ни разу не видел, чтобы эта штука сама по себе работала без `@EnableConfgurationProperties`

2023-02-23 22:25 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
Привязываться так, чтобы была гранулярность интерсепторов, а не все свалили в одну кучу и довольны. 
Может на каждое из значений, которое нам нужно извлечь, интерсептить будет слишком жирно (но я не уверен в этом, насколько затратно), но на каждое значение точно должен быть свой ключ. 

Вот я вижу издалека `ApiGatewayElement` и мне ни о чем это название не говорит, а если будет условный `ProfileIdElement` то сразу понятно, что это.

Посмотрел еще раз, а если бить на элементы, кажется что и не обойтись без интерсепторов.

Подумал еще6 если хочешь оставлять все в одном интерцепторе, то кажется логичным тогда и ключ называть `MetadataElement` и дать ему более понятное апи, то есть не просто геттер ключа, а на такущий момент геттер для айдишника профиля `getProfileId`

2023-02-24 08:15 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/configuration/GrpcConfiguration.kt
> +@Order(Ordered.HIGHEST_PRECEDENCE)
красивая константа просто))) на самом деле поправлю просто на 1 приоритет

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/GrpcProps.kt
> +@ConfigurationProperties(prefix = "platform.grpc")
да, @EnableConfigurationProperties находится в PlatformConfiguration 

Тут был PlatformLibraryApplication -- я развертывала приложуху и норм подсасывало

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/GrpcProps.kt
> +    data class GrpcServerProps(
оки

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/configuration/GrpcConfiguration.kt
> +    @ConditionalOnMissingBean(LoggingClientInterceptor::class)
Да, если ты решил обосрать платформенную либу и переопределить свой логгинг интерцептор(например, тебе нужно не логгировать какой-то ответ -- об этом пишется в ReadMe

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
геттер ключа в любом случае нужен, потому что именно так ты будешь извлекать элемент из короутинового контекста

Потом, уже после извлечения из контекста -- можешь просто получать значения обращая по полям, например так:
```
        val metadataElement = coroutineContext[MetadataElement]
        val metadata = Metadata(
            profileId =  metadataElement?.profileId
        )
```

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
переименовала в Metadata

2023-02-24 08:26 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/model/LogstashKey.kt
> +    const val ENDPOINT_KEY = "endpoint"
const val ENDPOINT_DIRECTION_KEY = "endpoint_direction" скорее тут определяем 

а ENDPOINT_KEY -- это просто название метода

2023-02-24 08:27 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +            logger.info(Markers.aggregate(markers)) { "$TYPE_CALL: ${method.serviceName}" }
нельзя писать инфо без {}, решила туда насытить полезным данным

2023-02-24 08:35 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/configuration/GrpcConfiguration.kt
> +    @ConditionalOnMissingBean(LoggingClientInterceptor::class)
сюда же и перенесла всю конфигурацию по всяким интерцепторам, чтобы не размазывать по разным классам

2023-02-25 09:27 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
через companion object можно назвать геттер нормально и вытаскивать сразу айдишник

`    companion object Key : CoroutineContext.Key<ApiGatewayElement>{
        suspend fun getProfileId() = coroutineContext[Key]?.profileId
    }`

2023-02-25 09:29 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingClientInterceptor.kt
> +            logger.info(Markers.aggregate(markers)) { "$TYPE_CALL: ${method.serviceName}" }
так необязательно полезные данные, вполне хватит просто сообщения что вот прошел реквест кмк

просто это выглядит как еще один маркер который зачем-то в сообщении

2023-02-25 09:30 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
давай сразу эту логику затащим в сам класс

`
    companion object Key : CoroutineContext.Key<ApiGatewayElement>{
        suspend fun getProfileId() = coroutineContext[Key]?.profileId
    }
`

2023-02-26 10:32 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
зачем? чтобы на каждое поле делать свой геттер?

2023-02-26 10:32 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/MetadataApiGatewayInterceptor.kt
> +class MetadataApiGatewayInterceptor : CoroutineContextServerInterceptor() {
получается по джавному, нет?

2023-02-26 19:07 UTC, Schuyweiz commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingServerInterceptor.kt
> +            logger.info(Markers.aggregate(markers)) { "request" }
А почему с маленькоц буквы или ты даже не задумываешься об этом?)

2023-02-26 19:45 UTC, Schuyweiz approved these changes

2023-02-26 19:53 UTC, WolfAlm commented on src/main/kotlin/ru/zveron/library/grpc/interceptor/LoggingServerInterceptor.kt
> +            logger.info(Markers.aggregate(markers)) { "request" }
логи по умолчанию обычно начинаются с маленькой буквой, скорее приняла как дефолт))

2023-02-26 19:54 UTC, merged